### ISSUE TITLE
在xml中添加出错

### ISSUE THREAD

**Issue by Jelly0726** [ome450901/SimpleRatingBar#40]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postAtTime(java.lang.Runnable, java.lang.Object, long)' on a null object reference
                                                                                at com.willy.ratingbar.ScaleRatingBar.fillRatingBar(ScaleRatingBar.java:69)
                                                                                at com.willy.ratingbar.BaseRatingBar.setRating(BaseRatingBar.java:220)
                                                                                at com.willy.ratingbar.BaseRatingBar.<init>(BaseRatingBar.java:101)
                                                                                at com.willy.ratingbar.BaseRatingBar.<init>(BaseRatingBar.java:68)
                                                                                at com.willy.ratingbar.AnimationRatingBar.<init>(AnimationRatingBar.java:24)
                                                                                at com.willy.ratingbar.ScaleRatingBar.<init>(ScaleRatingBar.java:25)
                                                                                at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                at com.wealthy.integratewealthy.activity.EvaluateActivity.onCreate(EvaluateActivity.java:53) 
                                                                                at android.app.Activity.performCreate(Activity.java:6303) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                at cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(Unknown Source) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                                at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5527) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 

 <com.willy.ratingbar.ScaleRatingBar
                xmlns:rb="http://schemas.android.com/apk/res-auto"
                android:id="@+id/storeRatingBar"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                rb:numStars="5"
                rb:rating="2"
                rb:starWidth="40dp"
                rb:starHeight="0dp"
                rb:starPadding="0dp"
                rb:stepSize="0.5"
                rb:isIndicator="false"
                rb:clickable="true"
                rb:scrollable="true"
                rb:clearRatingEnabled="true"
                rb:drawableEmpty="@mipmap/star_b_empty"
                rb:drawableFilled="@mipmap/star_b_full">
            </com.willy.ratingbar.ScaleRatingBar>

**Comment by ome450901** [comment]
Hello, thanks for your response.
I've found the problem, I will fix it ASAP.

You can use the previous version(v1.3.3) for now.

**Comment by ome450901** [comment]
I'v fix this issue, thanks for help!
