### ISSUE TITLE
crash report in fabric

### ISSUE THREAD

**Issue by oky2abbas** [ome450901/SimpleRatingBar#64]
Hello . **fabric** gave me the following error message that is related to your library.
Apparently this problem has been reported on the **HTC One A9** mobile phone with the **android 6** operating system.

**what's wrong ?**

```
Fatal Exception: java.lang.NumberFormatException: Invalid float: "۰.۰۴"
       at java.lang.StringToReal.invalidReal(StringToReal.java:63)
       at java.lang.StringToReal.initialParse(StringToReal.java:164)
       at java.lang.StringToReal.parseFloat(StringToReal.java:323)
       at java.lang.Float.parseFloat(Float.java:306)
       at com.willy.ratingbar.RatingBarUtils.calculateRating(RatingBarUtils.java:31)
       at com.willy.ratingbar.BaseRatingBar.handleMoveEvent(BaseRatingBar.java:396)
       at com.willy.ratingbar.BaseRatingBar.onTouchEvent(BaseRatingBar.java:371)
       at android.view.View.dispatchTouchEvent(View.java:9373)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2439)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1741)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2782)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2388)
       at android.view.View.dispatchPointerEvent(View.java:9614)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4436)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4292)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3816)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3875)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3841)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3971)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3849)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4028)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3821)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3875)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3841)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3849)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3821)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6150)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6118)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6072)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6253)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:216)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:202)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6224)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6276)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
       at android.view.Choreographer.doCallbacks(Choreographer.java:676)
       at android.view.Choreographer.doFrame(Choreographer.java:600)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5821)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

**Comment by ome450901** [comment]
Hi @dfmabbas, 

Thanks for issued this bug, I'll figure this out ASAP.
